bloom_user:
    resource: "@BloomUserBundle/Resources/config/routing.yml"
    prefix:   /

bloom_front:
    resource: "@BloomFrontBundle/Resources/config/routing.yml"
    prefix:   /

bloom_core:
    resource: "@BloomCoreBundle/Resources/config/routing.yml"
    prefix:   /api/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"